name: CI

on:
  push:
  pull_request:


jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Check build health
        run: yarn build

      - name: Check for regressions
        run: yarn lint